version: '3.3'

services:
  app:
    build:
      context: ./docker/apache
    container_name: tec_app
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
        #networks:
        # - localhost_net
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

networks:
  default:
    external:
      name: donweb
